---
language: node_js
node_js:
  - "4"
sudo: false
cache:
  directories:
    - node_modules
script:
  - npm run test:coverage
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
  - npm run doc
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash scripts/deploy.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash scripts/publish.sh