language: node_js
node_js:
- '4'
sudo: false
branches:
  only:
  - master
  - /\d+\.\d+\.\d+/
cache:
  directories:
  - node_modules
script:
- bash scripts/test.sh
- bash scripts/publish.sh
after_success:
- bash scripts/docs.sh
deploy:
  provider: npm
  email: sanchezmargareto@gmail.com
  api_key:
    secure: ulYfKJlVksYWyunImfNWgkqQhUNfpHlspKy8vBlmS9JUw8tdrgEAHR6Ri2OFuam1hc8TnLdQDQs0FbgAHcRBAKDjiTq3EdSv6lkMOc7GjaPkcaCXBO8TL3xnQ608iEAWtptEdKMuLr7JP+SCSqVlXgl3BxExmsg6WnKs6VpYOqDnCVQIl7NiBt8YaNDx+kmO312CghXt5QjCamx/a/BlWWrvi+BkzkgMHmmeuUru+njz9/Y53ZGWrwk1hwGrsn/B20IMqin3AuGMNWg9LSQTxC6iuBFFO3/575FWpens1utCaxVrHsLk86LSWJgWyn7v9c5VjIqBnDb8xVkovtGkMY2YL4okGfeuVVhouoDO+FfLQLBGAA5IfLIYCVLQDAleunceFNPskZwn/AzAmvv3pclL+YIrvHaPsfUOlkWrVNyJdNraem9BebYPHPIqilihBFiNcLEXuutsipuN1YAAo6795Daer1IsXSKaQgIXkMcOk784xVngUhJKkDS1XIGuivOVrQs2VQPQL1UZTEA6ib9M2SnBN/hbDlA+NuKylddCWmSaU0HZ6aSNfQWp4a/zd/Lo7WpsbiB3p9X7YJ44yIadHYRj2Zr3RBWQbE3JXYQcBV6JrtPJ4NKOikP4DLsEcIuZQiDHDmtJYrYkvGbEm8P1fPWutTqihHYGOlVynUc=
  on:
    tags: true
    repo: smarla/metadatio
