---
language: node_js
node_js:
  - "4"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
  - echo "Commit message > $TRAVIS_COMMIT_MSG"
script:
  - npm test
  - npm run test:coverage
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
after_success:
  - npm run doc
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash scripts/deploy.sh