application: metadatio
version: v0-2-0
runtime: php55
api_version: 1

handlers:

- url: /assets
  static_dir: assets

- url: /classes
  static_dir: classes

- url: /elements
  static_dir: elements

- url: /files
  static_dir: files

- url: /modules
  static_dir: modules

- url: /(index\.html)?
  script: index.html